### ISSUE TITLE
Install more recent operator-sdk tool in keda-tools

### ISSUE THREAD

**Issue by joelsmith** [kedacore/test-tools#136]
The `ghcr.io/kedacore/keda-tools` image should build a more recent version of the `operator-sdk` tool for use with the KEDA OLM operator.

Currently the tool is hard-coded to build v1.0.1
https://github.com/kedacore/test-tools/blob/main/tools/Dockerfile#L40-L48

This is causing some tests to fail when building via the image.

Note: I will assign this to myself and fix it. I just wanted to track it here so I didn't forget to do it before the next spin of the tools image.

**Comment by joelsmith** [comment]
Apparently I can't assign it to myself, but if one of the repo owners or other maintainers would like to assign it to me, that would be great. Thanks!

**Comment by JorTurFer** [comment]
Thanks!
